export const products = [
  {
    id: 1,
    img: "https://i.imgur.com/NGJEER1.png",
    title: "Inspiration Quote",
    link: "https://github.com/imtripleq/Javascript_project",
    skills: ["HTML", "CSS", "Vanilla JavaScript", "Auth0", "WebApi"],
  },
  {
    id: 2,
    img: "https://i.imgur.com/f4nA9tY.png",
    title: "E-Commerce Website",
    link: "https://github.com/imtripleq/qqq-react-project",
    skills: ["React.js", "Styled-component", "MUI-Icons"],
  },
  {
    id: 3,
    img: "https://i.imgur.com/FDYJBMS.png",
    title: "Personal Web Portfolio",
    link: "https://github.com/imtripleq/react_portfolio_mui",
    skills: ["React.js", "Material-ui", "MUI-Icons", "EmailJs", "React Typed"],
  },
  {
    id: 4,
    img: "https://i.imgur.com/wGbyfyF.png",
    title: "Food Picker",
    link: "https://github.com/imtripleq/react_project2",
    skills: ["React.js", "Material-ui", "MUI-Icons", "EmailJs", "Api"],
  },
];

export const skills = [
  { id: 1, name: "Vue.js", icon: "vuejs" },
  { id: 2, name: "React", icon: "react" },
  { id: 3, name: "JavaScript", icon: "javascript" },
  { id: 4, name: "TypeScript", icon: "typescript" },
  { id: 5, name: "Node.js", icon: "nodejs" },
  { id: 6, name: "React Native", icon: "react" },
  { id: 7, name: "Nuxt.js", icon: "nuxtjs" },
  { id: 8, name: "Contentful", icon: "contentful" },
  { id: 9, name: "VueStoreFront", icon: "vuejs" },
  { id: 10, name: "Jest", icon: "jest" },
  { id: 11, name: "Cypress", icon: "cypress" },
  { id: 12, name: "Git", icon: "git" },
  { id: 13, name: "HTML", icon: "html5" },
  { id: 14, name: "CSS", icon: "css3" },
  { id: 15, name: "SCSS", icon: "sass" },
  { id: 16, name: "Azure DevOps", icon: "azure" },
  { id: 17, name: "Kubernetes", icon: "kubernetes" },
  { id: 18, name: "Postman", icon: "postman" },
  { id: 19, name: "Python", icon: "python" },
  { id: 20, name: "Ruby", icon: "ruby" },
  // { id: 21, name: "Azure Fundamentals Certified", icon: "azure" },
  // { id: 22, name: "AWS Cloud Practitioner Certified", icon: "amazonaws" },
];

